apiVersion: v1
kind: Secret
metadata:
  name: {{ include "receipt-app.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "receipt-app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.dbPassword }}
  db-password: {{ .Values.secrets.dbPassword | b64enc | quote }}
  {{- else }}
  db-password: {{ "apppassword" | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.rabbitMQPassword }}
  rabbitmq-password: {{ .Values.secrets.rabbitMQPassword | b64enc | quote }}
  {{- else }}
  rabbitmq-password: {{ "guest" | b64enc | quote }}
  {{- end }}
